In [4]:
# the beginnning of libraries declaration part .

import numpy as np # a library for the Python programming language 
# adding support for large, multi-dimensional arrays and matrices
# along with a large collection of high-level mathematical functions to operate on these arrays .
import os #is a module provided by Python with the goal of interacting with the operating system .
import pandas  #  library for data manipulation and analysis .
from sklearn.model_selection import train_test_split # importing the function that splits the dataset into a specific sizes . 
from sklearn.feature_extraction.text import CountVectorizer # used to transform a given text into a vector on the basis of the frequency (count) of each word that occurs in the entire text.
from sklearn.linear_model import LogisticRegression # importing the logistic regression function from the sklearn library , and linear model class .
from sklearn import metrics # the metrics module implements several loss, score, and utility functions to measure classification performance.
import math #extends the list of mathematical functions. To use it

# the end of libraries declaration part .

In [5]:
#used to change the current working directory to specified path
# os.chdir("D:/DataMining/Databases_for_mining/dataset_for_soft_dev_and_comparison/text_mining/spam detection")

In [6]:
 spams = pandas.read_csv('spam_ham.txt' , sep="\t" , header=0)

In [7]:
spams

classe                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
print(type(spams)) #displaying the type of the dataset 

<class 'pandas.core.frame.DataFrame'>


In [9]:
print(spams.shape) #the dataset has 2 columns and 5572 rows 

(5572, 2)


In [10]:
print(spams.columns) #the dataset has 2 unique column attributes : classe and message  

Index(['classe', 'message'], dtype='object')


In [11]:
print(spams.dtypes) #the type of each attribute is object 

classe     object
message    object
dtype: object


In [12]:
print(spams.describe()) #discriptio of our dataset we notice that the most frequent class is ham with 4825 samples , and the most frequant message 
#is sorry , i'll call you latter with 30 appearences , there are 2 unique class attributes from a total of 5572 value and 5169 unique meessages 
#from the total of 5572 messages .

       classe                 message
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30


In [13]:
print(pandas.crosstab(index = spams["classe"] , columns="count")) #we notice that the ham class is the more frequent 

col_0   count
classe       
ham      4825
spam      747


# **preprocessing 1:**

In [14]:
spamsTrain, spamsTest = train_test_split(spams,train_size = 3572 , random_state = 1 , stratify = spams['classe'])
#splitting the corpus into training 3572 samples and testing set (the rest) , we notice the parametere stratify equal to class it means that 
#the division of the samples are processed according to the type of class , in more details there will be two groups called starta in which the first 
#will be the one of ham class , and the other is the one of spam class , then equal size of samples will be taken from both stratas , and assigned to 
#train , or test set .

In [15]:
freqTrain = pandas.crosstab(index=spamsTrain["classe"],columns="count")
print(freqTrain/freqTrain.sum())
#displaying the percentage of each class in the train corpus 

col_0      count
classe          
ham     0.865901
spam    0.134099


In [16]:
freqTest = pandas.crosstab(index=spamsTest["classe"],columns="count")
print(freqTest/freqTest.sum())
#displaying the percentage of each class in the test corpus 

col_0   count
classe       
ham     0.866
spam    0.134


In [17]:

parseur = CountVectorizer(binary=True)# If a token is present in a document, it is 1, if absent it is 0 regardless of its frequency of occurrence.
XTrain = parseur.fit_transform(spamsTrain['message'])#estimating and applying the parseur to our training set .
print(len(parseur.get_feature_names()))#printing the number of tokens because count vectorizer will extract a dictionary conatining tokens from our
#dataset , then each word in this dict will be considered as a column of the new built dataset (XTrain) , so  len(number of features) = len(number of tokens) 

6789


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [18]:
print(parseur.get_feature_names()) #printing the tokens and for sure it will be in a binary form 

['00', '000', '000pes', '0089', '01223585236', '01223585334', '0125698789', '02', '0207', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07046744435', '07090298926', '07099833605', '07123456789', '0721072', '07732584351', '07734396839', '07753741225', '0776xxxxxxx', '07781482378', '07786200117', '077xxx', '07808247860', '07821230901', '07880867867', '07946746291', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382', '08002888812', '08002986906', '08006344447', '0808', '08081263000', '08081560665', '0825', '083', '08448714184', '0845', '08452810073', '08452810075over18', '0870', '08700435505150p', '08700469649', '08700621170150p', '08701213186', '08701237397', '08701417012', '087016248', '08701752560', '087018728737', '0870241182716', '08702840625', '08704439680', '08704439680ts', '08706091795', '0870737910216yrs', '08707500020', '08707509020', '0870753331018', '08707808226', '0870

In [19]:
type(XTrain) #the XTrain is a sparse matrix means that the matrix is mostly composed of zeros rather than ones , and that's due to the countvectorizer 
#which was set as an appearance indicator of the token in each document 

scipy.sparse.csr.csr_matrix

In [20]:
mdtTrain = XTrain.toarray() #transforming the sparse matrix into a numpy array 
print(type(mdtTrain))

<class 'numpy.ndarray'>


In [21]:
print(mdtTrain.shape)#the training set is composed of 3572 rows and 6789 features (tokens)

(3572, 6789)


In [22]:
freq_mots = np.sum(mdtTrain , axis=0)#counting the number of accurence for each token in the whole corpus 
print(freq_mots)

[ 7 16  1 ...  1  1  1]


In [23]:
index = np.argsort(freq_mots) #sorting in an asc ordering the terms according to their number of occurences in the whole corpus 
print(index)

[3394 3820 3817 ... 5962 6756 6061]


In [24]:
imp = {'terme':np.asarray(parseur.get_feature_names())[index],'freq':freq_mots[index]}
print(pandas.DataFrame(imp))#printing the previous results list of terms 

         terme  freq
0        kaiez     1
1         mary     1
2     marriage     1
3         maps     1
4       manual     1
...        ...   ...
6784       and   522
6785        in   528
6786       the   647
6787       you  1042
6788        to  1091

[6789 rows x 2 columns]


# **Training 1 :**

In [25]:
modelFirst = LogisticRegression()#instanciating the logreg function 
modelFirst.fit(mdtTrain,spamsTrain['classe'])#fitting it into the training set 
print(modelFirst.coef_.shape)#printing the shape of coeficients parameters 


(1, 6789)


In [26]:
print(modelFirst.intercept_)#printng the sahpe of the bias 

[-4.9643061]


In [27]:
mdtTest = parseur.transform(spamsTest['message'])#transfroming the testing set in the same way as we did with training set to have ensure consistency
print(mdtTest.shape)

(2000, 6789)


In [28]:
from sklearn import tree
clf1 = tree.DecisionTreeClassifier()
clf1 = clf1.fit(mdtTrain,spamsTrain['classe'])

# **prediction 1:**

In [29]:
predTest = modelFirst.predict(mdtTest)#prediction for the testing set 

In [30]:
#confusino matrix 
mcTest = metrics.confusion_matrix(spamsTest['classe'],predTest)
print(mcTest)

#recall
print(metrics.recall_score(spamsTest['classe'],predTest,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTest,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTest,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTest))

[[1731    1]
 [  40  228]]
0.8507462686567164
0.9956331877729258
0.9175050301810864
0.9795


In [31]:
predTest = clf1.predict(mdtTest)#prediction for the testing set 

In [32]:
#confusino matrix 
mcTest = metrics.confusion_matrix(spamsTest['classe'],predTest)
print(mcTest)

#recall
print(metrics.recall_score(spamsTest['classe'],predTest,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTest,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTest,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTest))

[[1710   22]
 [  43  225]]
0.8395522388059702
0.9109311740890689
0.8737864077669903
0.9675


# **preprocessing 2:**

In [33]:
parseurBis = CountVectorizer(stop_words='english',binary=True, min_df = 10) #same as the previous preprocessing but enriched with stop word , and words that 
#appears less than 10 times elimination .
XTrainBis = parseurBis.fit_transform(spamsTrain['message'])#same as previous

print(len(parseurBis.get_feature_names()))#same as previous
mdtTrainBis = XTrainBis.toarray()#same as previous

541


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# **Training 2:**

In [34]:
modelBis = LogisticRegression()#same as previous
modelBis.fit(mdtTrainBis,spamsTrain['classe'])#same as previous

LogisticRegression()

In [35]:
clf2 = tree.DecisionTreeClassifier()
clf2 = clf2.fit(mdtTrainBis,spamsTrain['classe'])

# **Prediction 2:**

In [36]:
mdtTestBis = parseurBis.transform(spamsTest['message'])#same as previous
predTestBis = modelBis.predict(mdtTestBis)#same as previous

In [37]:
#confusion matrix
mcTestBis = metrics.confusion_matrix(spamsTest['classe'],predTestBis)
print(mcTestBis)

#recall
print(metrics.recall_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTestBis))

[[1731    1]
 [  37  231]]
0.8619402985074627
0.9956896551724138
0.9239999999999999
0.981


In [38]:
mdtTestBis = parseurBis.transform(spamsTest['message'])#same as previous
predTestBis = clf2.predict(mdtTestBis)#same as previous

In [39]:
#confusion matrix
mcTestBis = metrics.confusion_matrix(spamsTest['classe'],predTestBis)
print(mcTestBis)

#recall
print(metrics.recall_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTestBis,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTestBis))

[[1688   44]
 [  43  225]]
0.8395522388059702
0.8364312267657993
0.8379888268156424
0.9565


# **REMOVE TERMS WITH COEFFICIENTS NEARLY ZERO:**

In [40]:
coef_abs = np.abs(modelBis.coef_[0,:]) #taking the absolute value of the coefficients
thresholds = np.percentile(coef_abs,[0,25,50,75,90,100])#the values of treshhold are the ones that split the coefficient into 0.25 , 0.50 ...
print(thresholds)
indices = np.where(coef_abs > thresholds[1])#taking the values that are bigger than the second treshhold
print(len(indices[0]))
mdtTrainTer = mdtTrainBis[:,indices[0]]#taking only 0.25 of the coefficitn into consideration
mdtTestTer = mdtTestBis[:,indices[0]]
print(mdtTrainTer.shape)
print(mdtTestTer.shape)

[2.37540153e-03 1.77540082e-01 2.95911402e-01 6.09779140e-01
 1.05613226e+00 2.73460362e+00]
405
(3572, 405)
(2000, 405)


# **Training 3:**

In [41]:
modelTer = LogisticRegression()
modelTer.fit(mdtTrainTer,spamsTrain['classe'])

LogisticRegression()

In [42]:
clf3 = tree.DecisionTreeClassifier()
clf3 = clf3.fit(mdtTrainTer,spamsTrain['classe'])

# **Prediction 3:**

In [43]:
predTestTer = modelTer.predict(mdtTestTer)

In [44]:
#confusion matrix
mcTestTer = metrics.confusion_matrix(spamsTest['classe'],predTestTer)
print(mcTestTer)

#recall
print(metrics.recall_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTestTer))

#selected terms
sel_terms = np.array(parseurBis.get_feature_names())[indices[0]]

#sorted indices of the absolute value coefficients
sorted_indices = np.argsort(np.abs(modelTer.coef_[0,:]))

#print the terms and theirs coefficients
imp = {'term':np.asarray(sel_terms)[sorted_indices],'coef':modelTer.coef_[0,:][sorted_indices]}
print(pandas.DataFrame(imp))

[[1731    1]
 [  37  231]]
0.8619402985074627
0.9956896551724138
0.9239999999999999
0.981
        term      coef
0       best -0.152671
1       true  0.169354
2        sad -0.175941
3      haven -0.177285
4         im -0.177623
..       ...       ...
400      new  2.045639
401     150p  2.071956
402  service  2.222191
403    claim  2.273162
404       uk  2.744857

[405 rows x 2 columns]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [45]:
predTestTer = clf3.predict(mdtTestTer)

In [46]:
#confusion matrix
mcTestTer = metrics.confusion_matrix(spamsTest['classe'],predTestTer)
print(mcTestTer)

#recall
print(metrics.recall_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#precision
print(metrics.precision_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#F1-Score
print(metrics.f1_score(spamsTest['classe'],predTestTer,pos_label='spam'))

#accuracy rate
print(metrics.accuracy_score(spamsTest['classe'],predTestTer))

#selected terms
sel_terms = np.array(parseurBis.get_feature_names())[indices[0]]

#sorted indices of the absolute value coefficients
sorted_indices = np.argsort(np.abs(modelTer.coef_[0,:]))

#print the terms and theirs coefficients
imp = {'term':np.asarray(sel_terms)[sorted_indices],'coef':modelTer.coef_[0,:][sorted_indices]}
print(pandas.DataFrame(imp))

[[1694   38]
 [  40  228]]
0.8507462686567164
0.8571428571428571
0.8539325842696628
0.961
        term      coef
0       best -0.152671
1       true  0.169354
2        sad -0.175941
3      haven -0.177285
4         im -0.177623
..       ...       ...
400      new  2.045639
401     150p  2.071956
402  service  2.222191
403    claim  2.273162
404       uk  2.744857

[405 rows x 2 columns]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# **Deployment :**

In [47]:
#document to classify
doc = ['this is a new free service for you only']

#get its description
desc = parseurBis.transform(doc)
print(desc)

#which terms
print(np.asarray(parseurBis.get_feature_names())[desc.indices])

#dense representation
dense_desc = desc.toarray()

#apply var. selection
dense_sel = dense_desc[:,indices[0]]

#prediction of the class membership
pred_doc = modelTer.predict(dense_sel)
print(pred_doc)

#prediction of the class membership probabilities
pred_proba = modelTer.predict_proba(dense_sel)
print(pred_proba)

#checking - logit
logit = 1.823208 + 1.999089 + 2.201104 + modelTer.intercept_

#probability - logistic function
p_spam = 1/(1+math.exp(-logit))
print(p_spam)


  (0, 166)	1
  (0, 315)	1
  (0, 405)	1
['free' 'new' 'service']
['spam']
[[0.07816085 0.92183915]]
0.9141017335167014


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
